knowledge_engine:
  knowledge_base_id: 'https://entsoe.bluebird.com/ke/smartconnector'
  kb_name: 'ENTSO-E service'
  kb_description: 'ENTSO-E  service'
  prefixes:
    kb: "${KB_ID}/"
    ubmarket: "https://ubflex.bluebird.eu/market/"
    rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    s4ener: "https://saref.etsi.org/saref4ener/"
    xsd: "http://www.w3.org/2001/XMLSchema#"
    rdfs: "http://www.w3.org/2000/01/rdf-schema#"
    time: "http://www.w3.org/2006/time#"
  include:
    - "../dam/dam.yaml"
  graph_patterns:
    service:
      name: "service"
      description: "Information about service"
      pattern:
        - ' kb:service rdf:type saref:Device  ; saref:hasFunctionOfInterest kb:service_function . '
        - ' kb:service_function rdf:type saref:FunctionOfInterest; saref:hasCommandOfInterest kb:get_data_command . '
        - ' kb:get_data_command rdf:type saref:CommandOfInterest;  saref:hasCommandKind ubmarket:get_data_command ; '
        - '           saref:observes  ubmarket:MarketType .'
        
    start-command:
      name: "start-command"
      description: "Graph pattern for starting data acquisition task"
      prefixes:
        time: "http://www.w3.org/2006/time#"
      pattern:
        - ' kb:get_data_command  saref:observes ?market_uri . '
        - ' ?ts_interval_uri rdf:type time:Interval; time:hasBeginning ?ts_date_from; time:hasEnd ?ts_date_to .'
      result_pattern:
        - ' ?procedure_execution rdf:type saref:ProcedureExecution; saref:isExecutionOf kb:get_data_command;'
        - '    saref:hasStartTime ?time_start. '
    state-command:
      name: "state-command"
      description: "State service-command"
      prefixes:
        time: "http://www.w3.org/2006/time#"
      pattern:
        - ' ?procedure_execution rdf:type saref:ProcedureExecution; saref:isExecutionOf kb:get_data_command;'
        - '    saref:hasStartTime ?time_start; saref:hasEndTime ?end_time .'
    