knowledge_engine:
  knowledge_base_id: 'https://tge.pcss.pl/ke/smartconnector'
  kb_name: 'TGE dayahead offer'
  kb_description: 'TGE dayahead market agent'
  graph_patterns:
    ki-ts:
      name: "ki-ts"
      prefixes:
        rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xsd: "http://www.w3.org/2001/XMLSchema#"
        s4ener: "https://saref.etsi.org/saref4ener"
        foaf: "http://xmlns.com/foaf/0.1/"
        time: "http://www.w3.org/2006/time#"
        ubmarket: "https://ubeflex.bluebird.eu/market"
      pattern:
        - "?market rdf:type foaf:Agent ."
        - "?market ubmarket:isMarketType ubmarket:day_ahead."
        - "?offer rdf:type s4ener:TimeSeries ."
        - "?offer s4ener:producedBy ?market ."
        - '?offer s4ener:hasUpdateRate "PT60M"^^xsd:duration .'
        - "?offer s4ener:hasCreationTime ?offerCreationTime ."
        - '?offer s4ener:hasDuration "PT1440M"^^xsd:duration .'
    ki-dp:
      name: "ki-dp"
      prefixes:
        rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
        xsd: "http://www.w3.org/2001/XMLSchema#"
        saref: "https://saref.etsi.org/core/"
        s4ener: "https://saref.etsi.org/saref4ener"
        time: "http://www.w3.org/2006/time#"
      pattern:
        - "?offer rdf:type s4ener:TimeSeries ."
        - "?dp s4ener:belongsToTimeSeries ?offer ."
        - "?dp rdf:type s4ener:DataPoint ."
        - "?dp saref:hasTimestamp ?timestamp ."
        - "?dp saref:hasResult ?dpr ."
        - "?dpr saref:hasValue ?value ."
        - '?dpr saref:isMeasuredIn "PLNPerMegawattHour" .'
        - '?dp s4ener:hasDuration "PT60M"^^xsd:duration .'


#      answer-test:
#        name: "answer-test"
#        prefixes:
#          rdf: "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
#          xsd: "http://www.w3.org/2001/XMLSchema#"
#          saref: "https://saref.etsi.org/core/"
#          s4ener: "https://saref.etsi.org/saref4ener"
#          foaf: "http://xmlns.com/foaf/0.1/"
#          time: "http://www.w3.org/2006/time#"
#        pattern:
#          - "?sensor rdf:type saref:Sensor ."
#          - "?measurement saref:measurementMadeBy ?sensor ."
#          - "?measurement saref:isMeasuredIn saref:TemperatureUnit ."
#          - "?measurement saref:hasValue ?temperature ."